services:
  - name: sistema-receitas
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - src/**
        - receitas.cabal
      ignoredPaths:
        - README.md
        - assets/**